name: build

on: [push]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: oszimt-reconnector darwin arm64
          path: dist/oszimt-reconnector_darwin_arm64/oszimt-reconnector

      - uses: actions/upload-artifact@v3
        with:
          name: oszimt-reconnector darwin amd64
          path: dist/oszimt-reconnector_darwin_amd64_v1/oszimt-reconnector

      - uses: actions/upload-artifact@v3
        with:
          name: oszimt-reconnector windows amd64
          path: dist/oszimt-reconnector_windows_amd64_v1/oszimt-reconnector.exe